apiVersion: k3d.io/v1alpha5 
kind: Simple
image: rancher/k3s:v1.20.4-k3s1
metadata:
  name: k8s-lab
servers: 1 
agents: 3 
kubeAPI: 
  host: 0.0.0.0
  hostPort: '6441'
ports:
  - port: 8080:80 
    nodeFilters:
      - loadbalancer
# options:
#   k3s:
#     extraServerArgs:
#     - --no-deploy=traefik
